# Form implementation generated from reading ui file '.\drink_template.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_drink_template(object):
    def setupUi(self, drink_template):
        drink_template.setObjectName("drink_template")
        drink_template.resize(354, 284)
        drink_template.setWindowTitle("")
        self.verticalLayout = QtWidgets.QVBoxLayout(drink_template)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.add_to_tab_button = QtWidgets.QPushButton(drink_template)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.add_to_tab_button.sizePolicy().hasHeightForWidth())
        self.add_to_tab_button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.add_to_tab_button.setFont(font)
        self.add_to_tab_button.setObjectName("add_to_tab_button")
        self.gridLayout.addWidget(self.add_to_tab_button, 3, 1, 1, 1)
        self.quantity_spin_box = QtWidgets.QSpinBox(drink_template)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.quantity_spin_box.sizePolicy().hasHeightForWidth())
        self.quantity_spin_box.setSizePolicy(sizePolicy)
        self.quantity_spin_box.setMinimumSize(QtCore.QSize(0, 110))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.quantity_spin_box.setFont(font)
        self.quantity_spin_box.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.UpDownArrows)
        self.quantity_spin_box.setSuffix("")
        self.quantity_spin_box.setMinimum(1)
        self.quantity_spin_box.setObjectName("quantity_spin_box")
        self.gridLayout.addWidget(self.quantity_spin_box, 3, 0, 1, 1)
        self.drink_description_label = QtWidgets.QLabel(drink_template)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.drink_description_label.setFont(font)
        self.drink_description_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.drink_description_label.setObjectName("drink_description_label")
        self.gridLayout.addWidget(self.drink_description_label, 2, 0, 1, 2)
        self.drink_name_label = QtWidgets.QLabel(drink_template)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.drink_name_label.setFont(font)
        self.drink_name_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.drink_name_label.setObjectName("drink_name_label")
        self.gridLayout.addWidget(self.drink_name_label, 0, 0, 1, 2)
        self.price_label = QtWidgets.QLabel(drink_template)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.price_label.setFont(font)
        self.price_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.price_label.setObjectName("price_label")
        self.gridLayout.addWidget(self.price_label, 1, 0, 1, 2)
        self.gridLayout.setRowStretch(3, 1)
        self.verticalLayout.addLayout(self.gridLayout)

        self.retranslateUi(drink_template)
        QtCore.QMetaObject.connectSlotsByName(drink_template)

    def retranslateUi(self, drink_template):
        _translate = QtCore.QCoreApplication.translate
        self.add_to_tab_button.setText(_translate("drink_template", "Add to Tab"))
        self.quantity_spin_box.setPrefix(_translate("drink_template", "Quantity:   "))
        self.drink_description_label.setText(_translate("drink_template", "Description"))
        self.drink_name_label.setText(_translate("drink_template", "Drink Name"))
        self.price_label.setText(_translate("drink_template", "Price"))
