[tool.poetry]
name = "house-party-pos"
version = "0.2.1"
description = ""
authors = ["Brett Heinkel <bheinks@gmail.com>"]

[tool.poetry.dependencies]
python = "~3.11"
PyQt6 = "^6.4.0"
colorhash = "^1.2.1"
requests = "^2.28.1"
pillow = "^9.3.0"
pyqtdarktheme = "^2.1.0"
urlpath = "^1.2.0"

[tool.poetry.group.dev.dependencies]
aqtinstall = "^3.1.0"
pyinstaller = "^5.7.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
