# Form implementation generated from reading ui file '.\tab_row_template.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_tab_row_template(object):
    def setupUi(self, tab_row_template):
        tab_row_template.setObjectName("tab_row_template")
        tab_row_template.resize(1088, 161)
        self.verticalLayout = QtWidgets.QVBoxLayout(tab_row_template)
        self.verticalLayout.setContentsMargins(0, 10, 0, 0)
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.name_label = QtWidgets.QLabel(tab_row_template)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.name_label.setFont(font)
        self.name_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.name_label.setObjectName("name_label")
        self.horizontalLayout.addWidget(self.name_label)
        self.cost_label = QtWidgets.QLabel(tab_row_template)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cost_label.setFont(font)
        self.cost_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.cost_label.setObjectName("cost_label")
        self.horizontalLayout.addWidget(self.cost_label)
        self.quantity_label = QtWidgets.QLabel(tab_row_template)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.quantity_label.setFont(font)
        self.quantity_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.quantity_label.setObjectName("quantity_label")
        self.horizontalLayout.addWidget(self.quantity_label)
        self.total_label = QtWidgets.QLabel(tab_row_template)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.total_label.setFont(font)
        self.total_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.total_label.setObjectName("total_label")
        self.horizontalLayout.addWidget(self.total_label)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.remove_button = QtWidgets.QPushButton(tab_row_template)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.remove_button.setFont(font)
        self.remove_button.setStyleSheet("padding: 10px 20px")
        self.remove_button.setObjectName("remove_button")
        self.horizontalLayout_2.addWidget(self.remove_button)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.horizontalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 1)
        self.horizontalLayout.setStretch(2, 1)
        self.horizontalLayout.setStretch(3, 1)
        self.horizontalLayout.setStretch(4, 1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.line = QtWidgets.QFrame(tab_row_template)
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)

        self.retranslateUi(tab_row_template)
        QtCore.QMetaObject.connectSlotsByName(tab_row_template)

    def retranslateUi(self, tab_row_template):
        _translate = QtCore.QCoreApplication.translate
        tab_row_template.setWindowTitle(_translate("tab_row_template", "Form"))
        self.remove_button.setText(_translate("tab_row_template", "X"))
