# Form implementation generated from reading ui file '.\tab_row_template.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_tab_row_template(object):
    def setupUi(self, tab_row_template):
        tab_row_template.setObjectName("tab_row_template")
        tab_row_template.resize(1088, 76)
        self.verticalLayout = QtWidgets.QVBoxLayout(tab_row_template)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.drink_name_label = QtWidgets.QLabel(tab_row_template)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.drink_name_label.setFont(font)
        self.drink_name_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.drink_name_label.setObjectName("drink_name_label")
        self.horizontalLayout.addWidget(self.drink_name_label)
        self.drink_cost_label = QtWidgets.QLabel(tab_row_template)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.drink_cost_label.setFont(font)
        self.drink_cost_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.drink_cost_label.setObjectName("drink_cost_label")
        self.horizontalLayout.addWidget(self.drink_cost_label)
        self.drink_quantity_label = QtWidgets.QLabel(tab_row_template)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.drink_quantity_label.setFont(font)
        self.drink_quantity_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.drink_quantity_label.setObjectName("drink_quantity_label")
        self.horizontalLayout.addWidget(self.drink_quantity_label)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.remove_button = QtWidgets.QPushButton(tab_row_template)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.remove_button.sizePolicy().hasHeightForWidth())
        self.remove_button.setSizePolicy(sizePolicy)
        self.remove_button.setMinimumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.remove_button.setFont(font)
        self.remove_button.setObjectName("remove_button")
        self.gridLayout.addWidget(self.remove_button, 0, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 0, 1, 1)
        self.gridLayout.setColumnStretch(0, 1)
        self.gridLayout.setColumnStretch(2, 1)
        self.horizontalLayout.addLayout(self.gridLayout)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 1)
        self.horizontalLayout.setStretch(2, 1)
        self.horizontalLayout.setStretch(3, 1)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(tab_row_template)
        QtCore.QMetaObject.connectSlotsByName(tab_row_template)

    def retranslateUi(self, tab_row_template):
        _translate = QtCore.QCoreApplication.translate
        tab_row_template.setWindowTitle(_translate("tab_row_template", "Form"))
        self.drink_name_label.setText(_translate("tab_row_template", "Drink Name"))
        self.drink_cost_label.setText(_translate("tab_row_template", "Drink Cost"))
        self.drink_quantity_label.setText(_translate("tab_row_template", "Drink Quantity"))
        self.remove_button.setText(_translate("tab_row_template", "X"))
