# Form implementation generated from reading ui file '.\drink_template\drink_template.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_drink_template(object):
    def setupUi(self, drink_template):
        drink_template.setObjectName("drink_template")
        drink_template.resize(354, 284)
        drink_template.setWindowTitle("")
        self.verticalLayout = QtWidgets.QVBoxLayout(drink_template)
        self.verticalLayout.setObjectName("verticalLayout")
        self.photo_button = QtWidgets.QPushButton(parent=drink_template)
        self.photo_button.setFlat(True)
        self.photo_button.setObjectName("photo_button")
        self.verticalLayout.addWidget(self.photo_button)
        self.name_label = QtWidgets.QLabel(parent=drink_template)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.name_label.setFont(font)
        self.name_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.name_label.setObjectName("name_label")
        self.verticalLayout.addWidget(self.name_label)
        self.price_label = QtWidgets.QLabel(parent=drink_template)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.price_label.setFont(font)
        self.price_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.price_label.setObjectName("price_label")
        self.verticalLayout.addWidget(self.price_label)
        self.add_to_cart_button = QtWidgets.QPushButton(parent=drink_template)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.add_to_cart_button.setFont(font)
        self.add_to_cart_button.setStyleSheet("padding: 20px")
        self.add_to_cart_button.setObjectName("add_to_cart_button")
        self.verticalLayout.addWidget(self.add_to_cart_button)

        self.retranslateUi(drink_template)
        QtCore.QMetaObject.connectSlotsByName(drink_template)

    def retranslateUi(self, drink_template):
        _translate = QtCore.QCoreApplication.translate
        self.add_to_cart_button.setText(_translate("drink_template", "Add to Cart"))
