name: PyInstaller build
on:
  push:
    tags:
      - '*'
jobs:
  pyinstaller-build:
    runs-on: windows-latest
    steps:
      - name: Build
        id: build
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.12'
          spec: 'pos.spec'
          requirements: 'requirements.txt'
      - run: Compress-Archive -Path dist/pos -DestinationPath pos.zip
      - name: Create release
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
        run: |
          gh release create "$tag" --repo="$GITHUB_REPOSITORY" --title="$tag" --generate-notes pos.zip
