name: PyInstaller build
on: push
jobs:
  pyinstaller-build:
    runs-on: windows-latest
    steps:
      - name: Build
        id: build
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.12'
          spec: 'pos.spec'
          requirements: 'requirements.txt'
      - run: Compress-Archive -Path dist/pos -DestinationPath pos.zip
      - name: Create release
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ts=$(date +'%Y-%m-%d %H:%M:%S') && gh release create "$ts" --repo="$GITHUB_REPOSITORY" --title="$ts" --generate-notes pos.zip
