name: PyInstaller build
on: push
jobs:
  pyinstaller-build:
    runs-on: windows-latest
    steps:
      - name: Build
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.12'
          pyinstaller_ver: '==6.3.0'
          spec: 'pos.spec'
          requirements: 'requirements.txt'
          upload_exe_with_name: 'pos.exe'