name: PyInstaller build
on: push
jobs:
  pyinstaller-build:
    runs-on: windows-latest
    steps:
      - name: Build
        id: build
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.12'
          spec: 'pos.spec'
          requirements: 'requirements.txt'
          upload_exe_with_name: 'pos'
      - uses: actions/download-artifact@v4
      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
          EXE_PATH: ${{ steps.build.outputs.executable_path }}
        run: |
          gh release create "$tag" --repo="$GITHUB_REPOSITORY" --title="${GITHUB_REPOSITORY#*/} ${tag#v}" --generate-notes pos.zip
